#!/usr/bin/env bash
set -euo pipefail
export PATH="/opt/venv/bin:$PATH"
ts(){ date +"%Y-%m-%dT%H:%M:%S"; }
log(){ echo "$(ts) - $*"; }
COMFY_DIR="/workspace/ComfyUI"
CUSTOM_NODES="$COMFY_DIR/custom_nodes"
LORA_DIR="$COMFY_DIR/models/loras"
DIFF_DIR="$COMFY_DIR/models/diffusion_models"
CLIP_DIR="$COMFY_DIR/models/clip"
UPSCALE_DIR="$COMFY_DIR/models/upscale_models"
export GIT_TERMINAL_PROMPT=0
mkdir -p /workspace/.cache/pip /workspace/.cache/torch /workspace/.cache/huggingface
export PIP_CACHE_DIR="/workspace/.cache/pip"
export TORCH_HOME="/workspace/.cache/torch"
export HF_HOME="/workspace/.cache/huggingface"
declare -a NODES_REQUIRED=("ComfyUI-KJNodes|https://github.com/kijai/ComfyUI-KJNodes.git" "ComfyUI-WanVideoWrapper|https://github.com/kijai/ComfyUI-WanVideoWrapper.git" "ComfyUI-WanMoeKSampler|https://github.com/stduhpf/ComfyUI-WanMoeKSampler.git" "ComfyUI-PainterI2V|https://github.com/princepainter/ComfyUI-PainterI2V.git" "ComfyUI-FBCNN|https://github.com/Miosp/ComfyUI-FBCNN.git")
declare -a NODES_OPTIONAL=("ComfyUI-Impact-Pack|https://github.com/ltdrdata/ComfyUI-Impact-Pack.git" "ComfyUI-VideoHelperSuite|https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite.git" "rgthree-comfy|https://github.com/rgthree/rgthree-comfy.git" "was-node-suite-comfyui|https://github.com/WASasquatch/was-node-suite-comfyui.git" "comfyui_controlnet_aux|https://github.com/Fannovel16/comfyui_controlnet_aux.git" "ComfyUI_LayerStyle|https://github.com/chflame163/ComfyUI_LayerStyle.git" "ComfyUI_LayerStyle_Advance|https://github.com/chflame163/ComfyUI_LayerStyle_Advance.git" "ComfyLiterals|https://github.com/MNeMoNiCuZ/ComfyLiterals.git" "masquerade-nodes-comfyui|https://github.com/BadCafeCode/masquerade-nodes-comfyui.git" "ComfyUI-Easy-Use|https://github.com/yolain/ComfyUI-Easy-Use.git" "ComfyUI-TeaCache|https://github.com/kijai/ComfyUI-TeaCache.git" "ComfyUI_essentials|https://github.com/cubiq/ComfyUI_essentials.git" "cg-use-everywhere|https://github.com/chrisgoringe/cg-use-everywhere.git" "cg-image-picker|https://github.com/chrisgoringe/cg-image-picker.git" "ComfyUI_UltimateSDUpscale|https://github.com/ssitu/ComfyUI_UltimateSDUpscale.git" "ComfyUI_Comfyroll_CustomNodes|https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes.git" "ComfyUI_JPS-Nodes|https://github.com/JPS-GER/ComfyUI_JPS-Nodes.git" "ComfyUI-Frame-Interpolation|https://github.com/Kosinkadink/ComfyUI-Frame-Interpolation.git")
declare -a LORAS=("i2v_lightx2v_high_noise_model.safetensors|https://huggingface.co/lightx2v/Wan2.2-Lightning/resolve/main/Wan2.2-I2V-A14B-4steps-lora-rank64-Seko-V1/high_noise_model.safetensors" "i2v_lightx2v_low_noise_model.safetensors|https://huggingface.co/lightx2v/Wan2.2-Lightning/resolve/main/Wan2.2-I2V-A14B-4steps-lora-rank64-Seko-V1/low_noise_model.safetensors")
download_http(){ local url="$1"; local out="$2"; if [ -f "$out" ]; then log "   Exists: $(basename "$out")"; return; fi; mkdir -p "$(dirname "$out")"; local name="$(basename "$out")"; log "   Downloading: $name"; aria2c -c -x 16 -s 16 -k 1M -q -o "$name" -d "$(dirname "$out")" "$url" || log "❌ Failed: $name"; }
download_gdrive(){ local id="$1"; local out="$2"; if [ -f "$out" ]; then log "   Exists: $(basename "$out")"; return; fi; mkdir -p "$(dirname "$out")"; log "   Downloading (gdrive): $(basename "$out")"; gdown --id "$id" -O "$out" >/dev/null 2>&1 || log "❌ Failed (gdrive): $(basename "$out")"; }
download_civitai(){ local model_id="$1"; local out="$2"; if [ -f "$out" ]; then log "   Exists: $(basename "$out")"; return; fi; mkdir -p "$(dirname "$out")"; if [ -z "${CIVITAI_TOKEN:-}" ]; then log "⚠️  Skipping Civitai download $(basename "$out") (set CIVITAI_TOKEN env var)"; return; fi; log "   Downloading (civitai): $(basename "$out")"; curl -L -H "Authorization: Bearer ${CIVITAI_TOKEN}" "https://civitai.com/api/download/models/${model_id}" -o "$out" --fail || log "❌ Failed (civitai): $(basename "$out")"; }
ensure_comfy(){ log "🚀 Validating ComfyUI installation..."; if [ ! -d "$COMFY_DIR" ] || [ -z "$(ls -A "$COMFY_DIR" 2>/dev/null || true)" ]; then log "📥 Initializing ComfyUI from image..."; mkdir -p "$COMFY_DIR"; cp -a /ComfyUI/. "$COMFY_DIR"/; else log "✅ ComfyUI found in /workspace"; fi; mkdir -p "$CUSTOM_NODES" "$LORA_DIR" "$DIFF_DIR" "$CLIP_DIR" "$UPSCALE_DIR"; }
ensure_torch_stack(){ local want_t="2.8.0"; local want_tv="0.23.0"; local want_ta="2.8.0"; local cuda_tag="cu128"; local need="1"; python - <<PY || true
import importlib,sys
def v(m):
  try: return importlib.import_module(m).__version__
  except Exception: return None
t=v("torch"); tv=v("torchvision"); ta=v("torchaudio")
print("installed:",t,tv,ta)
ok=(t and t.startswith("${want_t}") and tv and tv.startswith("${want_tv}") and ta and ta.startswith("${want_ta}"))
sys.exit(0 if ok else 1)
PY
if [ "$?" = "0" ]; then log "✅ Torch stack already OK"; need="0"; fi
if [ "$need" = "1" ]; then log "📦 Installing Torch ${want_t} (CUDA ${cuda_tag})"; python -m pip install --no-cache-dir --upgrade pip setuptools wheel packaging; python -m pip uninstall -y torch torchvision torchaudio >/dev/null 2>&1 || true; python -m pip install --no-cache-dir --upgrade "torch==${want_t}+${cuda_tag}" "torchvision==${want_tv}+${cuda_tag}" "torchaudio==${want_ta}+${cuda_tag}" --index-url "https://download.pytorch.org/whl/${cuda_tag}" --extra-index-url "https://pypi.org/simple"; python -c "import torch; import torchvision; import torchaudio; print('torch',torch.__version__,'cuda',torch.version.cuda,'tv',torchvision.__version__,'ta',torchaudio.__version__)"; python -m pip freeze | grep -E "^(torch|torchvision|torchaudio)" > /workspace/torch-constraint.txt || true; fi
log "📦 Forcing known-good runtime deps (numpy/cupy/mediapipe/frontend)"; python -m pip install --no-cache-dir --upgrade --force-reinstall "numpy==1.26.4" "cupy-cuda12x==12.3.0" "mediapipe==0.10.21"; python -m pip install --no-cache-dir --upgrade "comfyui-frontend-package>=1.33.13"; }
ensure_sageattention(){ if python -c "import sageattention; print(getattr(sageattention,'__version__','unknown'))" >/dev/null 2>&1; then log "✅ sageattention already installed"; return; fi; log "⚙️  Installing sageattention (wheel-first)"; python -m pip install --no-cache-dir --upgrade "https://huggingface.co/Kijai/PrecompiledWheels/resolve/main/sageattention-2.2.0-cp312-cp312-linux_x86_64.whl" || (python -m pip install --no-cache-dir --upgrade sageattention || (rm -rf /tmp/SageAttention && git clone --depth=1 https://github.com/thu-ml/SageAttention.git /tmp/SageAttention && cd /tmp/SageAttention && python -m pip install --no-cache-dir -v .)); python -c "import sageattention; print('sageattention',getattr(sageattention,'__version__','unknown'))" || true; }
sync_nodes(){ log "🧩 Checking Custom Nodes..."; mkdir -p "$CUSTOM_NODES"; for entry in "${NODES_REQUIRED[@]}" "${NODES_OPTIONAL[@]}"; do IFS='|' read -r name url <<<"$entry"; local_path="$CUSTOM_NODES/$name"; if [ "$name" = "ComfyUI-PainterI2V" ] || [ "$name" = "ComfyUI-WanMoeKSampler" ]; then rm -rf "$local_path" || true; fi; if [ -d "$local_path" ]; then log "   Exists: $name"; continue; fi; log "   Cloning: $name"; git clone --depth=1 --recursive "$url" "$local_path" >/dev/null 2>&1 || log "❌ Setup Failed: $name"; done; log "✅ Custom Nodes Checked/Cloned"; }
install_node_requirements(){ log "📦 Checking Node Requirements..."; find "$CUSTOM_NODES" -maxdepth 2 -name requirements.txt | while read -r req_file; do grep -vE "^(torch|torchvision|torchaudio|opencv-python|opencv-python-headless|sageattention|cupy|numpy|triton)" "$req_file" > "${req_file}.clean" || true; if [ -s "${req_file}.clean" ]; then python -m pip install --no-cache-dir -r "${req_file}.clean" --no-deps >/dev/null 2>&1 || true; fi; rm -f "${req_file}.clean"; done; }
download_assets(){ log "⬇️  Checking/Downloading Lightning LoRAs..."; for entry in "${LORAS[@]}"; do IFS='|' read -r name url <<<"$entry"; download_http "$url" "$LORA_DIR/$name"; done; log "⬇️  Checking/Downloading Remix + UMT5 assets..."; download_http "https://huggingface.co/FX-FeiHou/wan2.2-Remix/resolve/main/NSFW/Wan2.2_Remix_NSFW_i2v_14b_high_lighting_v2.0.safetensors" "$DIFF_DIR/Wan2.2_Remix_NSFW_i2v_14b_high_lighting_v2.0.safetensors"; download_http "https://huggingface.co/FX-FeiHou/wan2.2-Remix/resolve/main/NSFW/Wan2.2_Remix_NSFW_i2v_14b_low_lighting_v2.0.safetensors" "$DIFF_DIR/Wan2.2_Remix_NSFW_i2v_14b_low_lighting_v2.0.safetensors"; download_http "https://huggingface.co/NSFW-API/NSFW-Wan-UMT5-XXL/resolve/main/nsfw_wan_umt5-xxl_fp8_scaled.safetensors" "$CLIP_DIR/nsfw_wan_umt5-xxl_fp8_scaled.safetensors"; log "⬇️  Checking/Downloading Upscaler..."; download_gdrive "1-pC6_7Lrmy3p-VAh-dGzvETRBUUAQzmV" "$UPSCALE_DIR/1xSkinContrast-SuperUltraCompact.pth"; log "⬇️  Checking/Downloading Civitai LoRAs..."; download_civitai "2312759" "$LORA_DIR/boobiefixer_high.safetensors"; download_civitai "2312689" "$LORA_DIR/boobiefixer_low.safetensors"; download_civitai "2284083" "$LORA_DIR/penis_fixer_high.safetensors"; download_civitai "2284089" "$LORA_DIR/penis_fixer_low.safetensors"; download_gdrive "1pwkyAiN15RxocVPsSEdebVUbhSaDUdIF" "$LORA_DIR/Instagirlv2.5-LOW.safetensors"; download_gdrive "1BfU6o4ICsN5o-NTB5PAoQEK5n1c1j4B0" "$LORA_DIR/Instagirlv2.5-HIGH.safetensors"; download_civitai "2073605" "$LORA_DIR/nsfwsks_high.safetensors"; download_civitai "2083303" "$LORA_DIR/nsfwsks_low.safetensors"; download_civitai "2190476" "$LORA_DIR/DR34ML4Y_nsfw_low.safetensors"; download_civitai "2176505" "$LORA_DIR/DR34ML4Y_nsfw_high.safetensors"; download_civitai "2496721" "$LORA_DIR/pussy_asshole_low.safetensors"; download_civitai "2496754" "$LORA_DIR/pussy_asshole_high.safetensors"; }
fix_extensions(){ if [ -d "$CUSTOM_NODES/ComfyLiterals/web" ]; then mkdir -p "$COMFY_DIR/web/extensions"; if [ ! -e "$COMFY_DIR/web/extensions/ComfyLiterals" ]; then ln -s "$CUSTOM_NODES/ComfyLiterals/web" "$COMFY_DIR/web/extensions/ComfyLiterals" || true; fi; fi; }
ensure_comfy
ensure_torch_stack
ensure_sageattention
sync_nodes
install_node_requirements
download_assets
fix_extensions
log "🚀 Starting ComfyUI on port 8188..."
cd "$COMFY_DIR"
exec python main.py --listen 0.0.0.0 --port 8188 --preview-method auto
